create table if not exists public.early_access (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(254) not null unique,
  company varchar(120),
  team_size varchar(40),
  locale varchar(2) not null check (locale in ('ar', 'en')),
  consent boolean not null check (consent is true),
  consented_at timestamptz not null default now(),
  source varchar(80),
  medium varchar(80),
  campaign varchar(80),
  network_hash char(64),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.early_access enable row level security;

revoke all on table public.early_access from anon, authenticated;
revoke all on sequence public.early_access_id_seq from anon, authenticated;

create index if not exists early_access_created_at_idx
  on public.early_access (created_at desc);

create index if not exists early_access_network_hash_created_idx
  on public.early_access (network_hash, created_at desc)
  where network_hash is not null;

comment on table public.early_access is
  'ScaleCX early-access requests. Direct Data API access is denied; writes go through the validated Edge Function.';
